---
title: "Modelling of acidification in fresh poultry sausages"
author: "N.-D. M. Luong"
data: "2021"
output: 
  html_document:
    theme: journal
runtime: shiny
---

```{r Sources, echo=FALSE, message=FALSE, warning=FALSE}
load("Data/output_model3.RData")
source("acidification_simulation_functions.R")
set.seed(408)
```

<style> div.main-container { max-width: 1400px; } </style>

# pH simulation
## One concentration of lactate and one time point 

```{r, echo=F}
inputPanel(
  #radioButtons("Atm_choice", label="Packaging condition", 
  #            choices = c("Air", "MAP1:70%O2-30%CO2", "MAP2:50%CO2-50%N2")),
  sliderInput("Lactate_choice", label="Lactate (% w/w)", min=0, max=3, value=2, step=0.05),
  sliderInput("Time_choice", label="Time (days)", min=0, max=22, value=10, step=1),
  actionButton("Simulation_button", label="Simulation")
)

Simulation_Event <- eventReactive(input$Simulation_button, {
  lactate_for_sim <- input$Lactate_choice ## chosen lactate concentrations for simulation
  time_for_sim <- input$Time_choice  ## chosen lactate concentrations for simulation
  simulated_pH <- f_pred_pH(jd = mcmctot, 
                            time_pred = time_for_sim, 
                            lactate_pred = lactate_for_sim)
  estimated_pH <- as.data.frame(t(apply(simulated_pH$pH_pred, 3, quantile, probs=c(0.025, 0.5, 0.975))))
  rownames(estimated_pH) <- c("Air", "MAP1:70%O2-30%CO2", "MAP2:50%CO2-50%N2")
  colnames(estimated_pH) <- c("2.5% quantile", "Median", "97.5% quantile")
  estimated_pH
})
renderTable({
  Simulation_Event()
}, digits=2, rownames = T)

```

## Several concentrations of lactate and several time points
```{r, echo=F}
inputPanel(
  numericInput("Lactate_nb", label="Total number of concentrations ", 3, step=1, min=1, max=10),
  sliderInput("Lactate_range_choice", label="Lactate range (% w/w)", min=0, max=3, value=c(0,2), step=0.05),
  numericInput("Time_nb", label="Total number of time points",3, step=1, min=1, max=20),
  sliderInput("Time_range_choice", label="Time range (days)", min=0, max=22, value=c(2,15), step=1),
  actionButton("Simulation_range_button", label="Simulation (this may take a while)")
)

Simulation_range_Event <- eventReactive(input$Simulation_range_button, {
  lactate_for_sim <- seq(from = input$Lactate_range_choice[1], 
                         to = input$Lactate_range_choice[2],
                         length.out = input$Lactate_nb)
  time_for_sim <- seq(from = input$Time_range_choice[1], 
                      to = input$Time_range_choice[2],
                      length.out = input$Time_nb)
  simulated_pH_range <- f_pred_pH(jd = mcmctot, 
                                time_pred = time_for_sim, 
                                lactate_pred = lactate_for_sim)
  pH_IC_band <- f_IC_Band(predicted_data = simulated_pH_range)
  write.table(pH_IC_band, file="simulated_dataset.txt", sep="\t", dec=".")
  head(pH_IC_band, n = 10)
})
```


```{r, echo=F}
renderTable({
  Simulation_range_Event()
}, digits=2, rownames = T)
```
(only the first 10 lines of the simulated dataset are shown)
```{r, echo=F}
downloadHandler(filename = function() { 
    return("Simulation_output.csv")
  }, content = function(file) {
   write.csv(read.table(file="simulated_dataset.txt", h=T), file)
 })
```



